// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LCI")>]
[<assembly: AssemblyProductAttribute("LCI")>]
[<assembly: AssemblyDescriptionAttribute("a dsl to express First Order Logic expressions")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LCI"
    let [<Literal>] AssemblyProduct = "LCI"
    let [<Literal>] AssemblyDescription = "a dsl to express First Order Logic expressions"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
